Properly failing when sbatch fails
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>

diff --git a/hpc/shark-submit b/hpc/shark-submit
--- a/hpc/shark-submit
+++ b/hpc/shark-submit
@@ -150,7 +150,12 @@ submit_slurm() {
 		info "Submitting shark job with command: $cmd"
 
 		# Go, go, go!
-		eval $cmd || error "Error when submitting job to the queue"
+		eval $cmd
+		if [ $? -ne 0 ]
+		then
+			error "Error when submitting job to the queue"
+			exit 1
+		fi
 	fi
 }
 
